#This document is an example of a simple function in R to calculate the number of cells per ml in a Burker-Turk chamber. The function assumes that 2 times (2 seperate grids of the chamber) 25 squares are counted and takes the following arguments:
#'Count_1'= the amount of cels counted in 25 squares in grid 1.
#'Count_2 = the amount of cels counted in 25 squares in grid 2.
#'Dilution' = the dilution factor (e.g. for staining the cells).
#'Volume' = the total amount of volume in which the cells are suspended (in milliliters).

#The output generated by the function is:
#'Cells/ml' = number of cells per ml in the suspension counted
#'Total Cells' = the total number of cells in the suspension

CountingCells <- function(Count_1, Count_2, Dilution, volume){
  
  
  
  averageCount <- mean(Count_1, Count_2)
  
  number_cells_ml <- (averageCount*Dilution*1E4)
  
  Total_cells <- (number_cells_ml*volume)
  
  
  
  number_cells_ml <- format(number_cells_ml, scientific = TRUE)
  
  
  Total_cells <- format(Total_cells, scientific = TRUE)
  
  
  
  cat("Cells/ml =", number_cells_ml,      
      "Total Cells =", Total_cells)
  
  
}

CountingCells(23,34,10,5)

